-
  name: Install and configure httpd
  hosts: servers
  become: yes  # This assumes you need elevated privileges to install packages and manage services
  tasks:
    - name: Install apache2 package
      apt:
        name: apache2
        state: present

    - name: Ensure httpd service is enabled
      service:
        name: apache2
        state: started
        enabled: yes
