---
- name: Create AWS Target Group and Register EC2 Instances
  hosts: localhost
  connection: local
  #hosts: servers
  gather_facts: False
  tags: provisioning
  tasks:
    - name: Include deployment playbook
      include: deploy.yml
  
